account/urls.py
from django.urls import path

from .views import (LoginView, LogoutView, RegisterView, ValidateView, ProfileView, ResendValidationView,
                    PasswordResetView, PasswordResetConfirmView, CookiesView, PasswordChangeView, AccountDeleteView,
                    AccountUpdateView)


app_name = 'account'

urlpatterns = [
    path('create-account/', RegisterView.as_view(), name='register'),
    path('validate/<slug:uidb64>/<slug:token>/', ValidateView.as_view(), name='validate'),
    path('validate/', ResendValidationView.as_view(), name='resend_validate'),
    path('login/', LoginView.as_view(), name='login'),
    path('login/password/', PasswordResetView.as_view(), name='password_reset'),
    path('login/password/<slug:uidb64>/<slug:token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('account/', AccountUpdateView.as_view(), name='update'),
    path('account/password/', PasswordChangeView.as_view(), name='password'),
    path('account/delete/', AccountDeleteView.as_view(), name='delete'),
    path('cookies/', CookiesView.as_view(), name='cookies'),
    path('<slug:slug>/', ProfileView.as_view(), name='profile'),
]

api/urls.py
from django.urls import (path, include)
from rest_framework import routers

from .views import (OfferViewSet, UserViewSet, AuctionViewSet, BidViewSet, CategoryViewSet)


router = routers.DefaultRouter()
router.register(r'auctions', AuctionViewSet)
router.register(r'bids', BidViewSet)
router.register(r'categories', CategoryViewSet)
router.register(r'offers', OfferViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('rest_framework.urls', namespace='rest_framework'))
]

auction/urls.py
from django.urls import path

from .views import (AuctionView, AuctionAboutView, AuctionCreateView, AuctionUpdateView, AuctionDeleteView,
                    AuctionResultsView, AuctionUpdateEmailView, AuctionUpdateLayoutView)


app_name = 'auction'

urlpatterns = [
    path('<slug:user>/create-auction/multi/', AuctionCreateView.as_view(), name='create'),
    path('<slug:user>/<slug:auction>/', AuctionView.as_view(), name='auction'),
    path('<slug:user>/<slug:auction>/about/', AuctionAboutView.as_view(), name='about'),
    path('<slug:user>/<slug:auction>/edit/', AuctionUpdateView.as_view(), name='update'),
    path('<slug:user>/<slug:auction>/edit/email/', AuctionUpdateEmailView.as_view(), name='update_email'),
    path('<slug:user>/<slug:auction>/edit/layout/', AuctionUpdateLayoutView.as_view(), name='update_layout'),
    path('<slug:user>/<slug:auction>/delete/', AuctionDeleteView.as_view(), name='delete'),
    path('<slug:user>/<slug:auction>/winning-bids/', AuctionResultsView.as_view(), name='results'),
]

offer/urls.py
from django.urls import path

from .views import (OfferView, OfferCreateView, OfferListView, OfferUpdateView, OfferDeleteView,
                    OfferListAdministrationView, OfferUpdateAdministrationView, OfferDeleteAdministrationView,
                    OfferSearchView)


app_name = 'offer'

urlpatterns = [
    path('<slug:user>/<slug:auction>/create-offer/', OfferCreateView.as_view(), name='create'),
    path('<slug:user>/<slug:auction>/offers/', OfferListAdministrationView.as_view(), name='list_administration'),
    path('<slug:user>/<slug:auction>/offers/<slug:category>/', OfferListAdministrationView.as_view(),
         name='list_administration_category'),
    path('<slug:user>/<slug:auction>/offer/<int:pk>/edit/', OfferUpdateAdministrationView.as_view(),
         name='update_administration'),
    path('<slug:user>/<slug:auction>/offer/<int:pk>/delete/', OfferDeleteAdministrationView.as_view(),
         name='delete_administration'),
    path('<slug:user>/<slug:auction>/tag:<slug:tag>/', OfferSearchView.as_view(), name='search_tag'),
    path('<slug:user>/<slug:auction>/category:<slug:category>/', OfferSearchView.as_view(), name='search_category'),
    path('<slug:user>/<slug:auction>/category:<slug:category>/tag:<slug:tag>/', OfferSearchView.as_view(),
         name='search_items'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/', OfferListView.as_view(), name='list'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/<int:pk>/', OfferView.as_view(), name='view'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/<int:pk>/edit/', OfferUpdateView.as_view(), name='update'),
    path('<slug:user>/<slug:auction>/<slug:auctionee>/<int:pk>/delete/', OfferDeleteView.as_view(), name='delete'),
]

bid/models.py
from decimal import Decimal

from django.conf import settings
from django.core.mail import EmailMessage
from django.db import models
from django.shortcuts import reverse
from django.utils import (timezone, dateformat)

from django_q.tasks import async_task

from core.templatetags.core_tags import format_currency


class BidManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
            .select_related('user') \
            .select_related('pinch_hitter') \
            .select_related('offer') \
            .select_related('offer__category') \
            .select_related('offer__user') \
            .order_by('-amount')


class Bid(models.Model):
    MODES = [
        'donation_complete',
        'donation_unverified',
        'pending_alert',
        'pending_donation',
        'donation_late'
    ]

    user = models.ForeignKey('account.User', related_name='bids', on_delete=models.CASCADE)
    pinch_hitter = models.ForeignKey('account.User', related_name='pinch_hits', on_delete=models.CASCADE, null=True,
                                     blank=True)
    anonymous = models.BooleanField(default=False)
    offer = models.ForeignKey('offer.Offer', related_name='bids', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(blank=True, max_digits=6, decimal_places=2, default=Decimal('0.00'))
    donation_deadline = models.DateTimeField(blank=True, null=True)
    winner_alert_email = models.TextField(blank=True)
    winner_alert_email_date = models.DateTimeField(blank=True, null=True)
    auctionee_sent_winner_details_email = models.TextField(blank=True)
    auctionee_sent_winner_details_email_date = models.DateTimeField(blank=True, null=True)
    winner_sent_auctionee_details_email = models.TextField(blank=True)
    winner_sent_auctionee_details_email_date = models.DateTimeField(blank=True, null=True)
    pinch_hitter_sent_winner_details_email = models.TextField(blank=True)
    pinch_hitter_sent_winner_details_email_date = models.DateTimeField(blank=True, null=True)
    winner_sent_pinch_hitter_details_email = models.TextField(blank=True)
    winner_sent_pinch_hitter_details_email_date = models.DateTimeField(blank=True, null=True)

    donated = models.DateTimeField(blank=True, null=True)
    receipt = models.TextField(blank=True)
    has_donated = models.BooleanField(default=False, db_index=True)

    objects = BidManager()

    def __str__(self):
        return str(self.amount)

    @property
    def donate_by(self):
        return self.donation_deadline or self.offer.auction.donation_deadline

    def can_donate(self, top_bids):
        check_valid = any([True for b in top_bids if b.id == self.id])
        return True if check_valid and self.donate_by > timezone.now() else False

    @property
    def hash(self):
        return settings.FANTICS_HASH.encode(self.id)

    @property
    def status(self):
        for state in ['donation_complete', 'donation_unverified', 'pending_alert', 'pending_donation', 'donation_late']:
            if getattr(self, state):
                return state

    @property
    def donation_complete(self):
        # donation confirmed
        return self.has_donated

    @property
    def donation_unverified(self):
        # no confirmation, but there is a receipt to confirm, so even if it's post deadline we're good
        return True if not self.donation_complete and self.receipt else False

    @property
    def pending_alert(self):
        # no confirmation, no receipt, but also no e-mail went out so deadline doesn't apply
        return True if not self.donation_complete \
                       and not self.donation_unverified \
                       and not self.winner_alert_email_date else False

    @property
    def pending_donation(self):
        # no confirmation, no receipt, email went out and we're inside the deadline, so we're waiting
        return True if not self.donation_complete \
                       and not self.donation_unverified \
                       and not self.pending_alert \
                       and timezone.now() < self.donate_by else False

    @property
    def donation_late(self):
        # no confirmation, no receipt, email went out and we're outside the deadline, so it's late
        return True if not self.donation_complete \
                       and not self.donation_unverified \
                       and not self.pending_alert \
                       and timezone.now() > self.donate_by else False

    def generate_winner_donation_alert(self):
        email = self.offer.auction.winner_alert_email_body.format(**{
            'bidder': self.user.display_name,
            'auctionee': self.offer.user.display_name,
            'category': self.offer.category.name,
            'amount': "{} ({})".format(
                format_currency(self.amount, self.offer.auction.currency),
                self.offer.auction.currency
            ),
            'deadline': "{} ({})".format(
                dateformat.format(timezone.localtime(self.donate_by), "m/d/Y H:i"),
                self.offer.auction.timezone
            ),
            'donation_instructions': self.offer.auction.beneficiary_donation_information,
            'donation_website': self.offer.auction.beneficiary_donation_website,
            'link': "{}{}".format(settings.BASE_URL, reverse('bid:donate', kwargs={
                'user': self.offer.auction.user.slug,
                'auction': self.offer.auction.slug,
                'bidder': self.offer.user.slug,
                'hash': self.hash
            }))
        })

        return str(email)

    def _auctionee_details_email(self, email):
        return str(email.format(**{
            'bidder': self.user.display_name,
            'auctionee': self.offer.user.display_name,
            'email': self.offer.user.email,
            'category': self.offer.category.name,
            'amount': "{} ({})".format(
                format_currency(self.amount, self.offer.auction.currency),
                self.offer.auction.currency
            )
        }))

    def _pinch_hitter_details_email(self, email):
        return str(email.format(**{
            'bidder': self.user.display_name,
            'auctionee': self.offer.user.display_name,
            'pinch_hitter': self.pinch_hitter.display_name,
            'email': self.offer.user.email,
            'category': self.offer.category.name,
            'amount': "{} ({})".format(
                format_currency(self.amount, self.offer.auction.currency),
                self.offer.auction.currency
            )
        }))

    # the auctionee's details to send to the winning bidder
    def generate_winner_sent_auctionee_details_email(self):
        return self._auctionee_details_email(self.offer.auction.auctionee_details_to_winner_email_body)

    # the winning bidder's details to send to the auctionee
    def generate_auctionee_sent_winner_details_email(self):
        return self._auctionee_details_email(self.offer.auction.winner_details_to_auctionee_email_body)

    # the pinch-hitter's details to send to the winning bidder
    def generate_winner_sent_pinch_hitter_details_email(self):
        return self._pinch_hitter_details_email(self.offer.auction.pinch_hitter_details_to_winner_email_body)

    # the winning bidder's details to send to the pinch-hitter
    def generate_pinch_hitter_sent_winner_details_email(self):
        return self._pinch_hitter_details_email(self.offer.auction.winner_details_to_pinch_hitter_email_body)

    # send e-mail to winning bidder with donation information
    def email_winner_donation_alert(self, async=False):
        subject = "[{}] {}".format(self.offer.auction.title, self.offer.auction.winner_alert_email_subject)
        from_email = "<Fantics> {}".format(settings.DEFAULT_FROM_EMAIL)
        to_email = "<{}> {}".format(self.user.display_name, self.user.email)
        reply_to = "<{}> {}".format(self.offer.auction.contact_name, self.offer.auction.contact_email)

        if not async:
            email = EmailMessage(subject, self.winner_alert_email, from_email, to=[to_email, ], reply_to=[reply_to, ])

            return email.send(fail_silently=True)

        else:
            async_task('core.tasks.send_email', subject, self.winner_alert_email, from_email, to_email, reply_to)

    # send e-mail to auctionee with winning bidder details
    def email_winner_details_to_auctionee(self):
        email = EmailMessage(
            "[{}] {}".format(self.offer.auction.title, self.offer.auction.winner_details_to_auctionee_email_subject),
            self.auctionee_sent_winner_details_email,
            "<Fantics> {}".format(settings.DEFAULT_FROM_EMAIL),
            to=[self.user.email],
            reply_to=["<{}> {}".format(self.offer.auction.contact_name, self.offer.auction.contact_email)]
        )

        return email.send(fail_silently=True)

    # send e-mail to winning bidder with auctionee details
    def email_auctionee_details_to_winner(self):
        email = EmailMessage(
            "[{}] {}".format(self.offer.auction.title, self.offer.auction.auctionee_details_to_winner_email_subject),
            self.winner_sent_auctionee_details_email,
            "<Fantics> {}".format(settings.DEFAULT_FROM_EMAIL),
            to=[self.user.email],
            reply_to=["<{}> {}".format(self.offer.auction.contact_name, self.offer.auction.contact_email)]
        )

        return email.send(fail_silently=True)

    # send e-mail to pinch hitter with winning bidder details
    def email_winner_details_to_pinch_hitter(self):
        email = EmailMessage(
            "[{}] {}".format(self.offer.auction.title, self.offer.auction.winner_details_to_pinch_hitter_email_subject),
            self.pinch_hitter_sent_winner_details_email,
            "<Fantics> {}".format(settings.DEFAULT_FROM_EMAIL),
            to=[self.user.email],

offer/models.py
from decimal import Decimal

from django.db import models
from django.db.models.functions import Lower
from django.utils.functional import cached_property

from taggit.managers import TaggableManager

from bid.models import Bid
from core.helpers import (file_name, teaser)
from tags.models import FanticsTaggedItem


class OfferManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
            .select_related('user') \
            .select_related('category') \
            .prefetch_related('tags') \
            .order_by(Lower('user__display_name')) \
            .annotate(
                count_bids=models.Count('bids', distinct=True)
            )


def offer_image_name(instance, filename):
    return '/'.join(['offers', file_name(filename)])


class Offer(models.Model):
    user = models.ForeignKey('account.User', related_name='offers', on_delete=models.CASCADE)
    auction = models.ForeignKey('auction.Auction', related_name='offers', on_delete=models.CASCADE)
    category = models.ForeignKey('category.Category', related_name='offers', on_delete=models.CASCADE)
    notes = models.TextField(blank=False)
    tags = TaggableManager(through=FanticsTaggedItem, blank=True)
    deadline = models.DateField(null=True, blank=True, help_text='The date by which you will have delivered the offer '
                                                                 'to the winning bidder(s)')
    minimum_bid = models.DecimalField(blank=True, max_digits=8, decimal_places=2, default=Decimal('1.00'))
    quantity = models.IntegerField(default=1, help_text="How many of the item you're offering can be individually bid "
                                                        "on")
    image = models.ImageField(null=True, blank=True, upload_to=offer_image_name)
    information_website = models.URLField(blank=True, max_length=255)

    objects = OfferManager()

    @property
    def teaser(self):
        return teaser(self.notes, 200)

    @cached_property
    def _bids(self):
        return self.bids.all()

    @property
    def top_bids(self):
        return self._bids[:self.quantity] if self.count_bids else []

    @property
    def must_bid(self):
        try:
            return Decimal(self.top_bids[self.quantity-1].amount + 1)
        except IndexError:
            return self.minimum_bid

    @property
    def total(self):
        total = 0

        for bid in self.top_bids:
            if bid.has_donated:
                total += bid.amount

        return total

    def __str__(self):
        return "{}: {} (x{})".format(self.user.display_name, self.category.name, self.quantity)

offer/templates/offer/_offer_card.html
{% load core_tags %}

<div class="col-md-4 my-3">
    <div class="card">
        <div class="card-header">
            <a href="{% url 'offer:search_category' auction.user.slug auction.slug offer.category.slug %}">{{ offer.category }}</a>
            <span class="float-right">
                {% if auction.is_archived %}
                    <strong>{% currency offer.total auction.currency %}</strong>
                {% elif offer.count_bids %}
                    <strong>{% currency offer.must_bid auction.currency %}</strong>
                {% else %}
                    <strong>{% currency offer.minimum_bid auction.currency %}</strong>
                {% endif %}
            </span>
        </div>
        <div class="card-body">
            <h5 class="card-title"><a href="{% url 'offer:list' auction.user.slug auction.slug offer.user.slug %}">{{ offer.user }}</a></h5>
            <p class="card-text">{{ offer.teaser }}</p>
            <div class="row">
                <div class="col-md-6">
                    <a href="{% url 'offer:view' auction.user.slug auction.slug offer.user.slug offer.pk %}" class="btn btn-primary">View</a>
                </div>
                <div class="col-md-6 text-md-right">
                    {% if auction.bidding_open and request.user.is_authenticated %}
                        <a href="{% url 'offer:view' auction.user.slug auction.slug offer.user.slug offer.pk %}#Bid" class="btn btn-warning">Bid!</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card-footer text-truncate">
            {% for tag in offer.tags.all %}
                <small><a href="{% url 'offer:search_tag' auction.user.slug auction.slug tag.slug %}" class="text-muted">#{{ tag }}</a></small>
            {% endfor %}
        </div>
    </div>
</div>

offer/templates/offer/list.html
{% extends 'auction/base.html' %}
{% load bootstrap4 core_tags %}

{% block content %}

    <h1>Your offers</h1>

    {% if auction.signups_open %}
        {% if not auction.max_offers_per_user or offer_list|length < auction.max_offers_per_user %}
            <p class="text-right">
                <a href="{% url 'offer:create' auction.user.slug auction.slug %}" class="btn btn-primary">
                    <i class="fa fa-plus-square"></i> Add offer
                </a>
            </p>
        {% endif %}
    {% endif %}

    {% if offer_list %}
        <table class="table">
            <thead>
                <tr>
                    <th>Offer</th>
                    <th>Minimum bid</th>
                    <th>Quantity</th>
                    <th>Deadline</th>
                    <th>Bids</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for offer in offer_list %}
                    <tr>
                        <td>{{ offer.category.name }}</td>
                        <td>{% currency offer.minimum_bid auction.currency %}</td>
                        <td>{{ offer.quantity }}</td>
                        <td>{{ offer.deadline|default_if_none:auction.offer_deadline }}</td>
                        <td>{{ offer.count_bids|default_if_none:0 }}</td>
                        <td class="text-right">
                            <div class="btn-group" role="group" aria-label="Administration">
                                <a class="btn btn-success" href="{% url 'offer:view' auction.user.slug auction.slug offer.user.slug offer.pk %}" title="View">
                                    <i class="fa fa-eye"></i> <span class="sr-only">View</span>
                                </a>
                                {% if auction.signups_open %}
                                <a class="btn btn-info" href="{% url 'offer:update' auction.user.slug auction.slug request.user.slug offer.pk %}" title="Edit">
                                    <i class="fa fa-cog"></i> <span class="sr-only">Edit</span>
                                </a>
                                <a class="btn btn-warning" href="{% url 'offer:delete' auction.user.slug auction.slug request.user.slug offer.pk %}" title="Delete">
                                    <i class="fa fa-trash"></i> <span class="sr-only">Delete</span>
                                </a>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p class="alert alert-info">You have no offers in this auction</p>
    {% endif %}

{% endblock %}

offer/templates/offer/view.html
{% extends 'auction/base.html' %}
{% load bootstrap4 core_tags %}

{% block javascript_body %}
<script>
    var offerSocket;
    var link = window.location.host + '/offer/{{ offer.pk }}/';

    if (location.protocol !== 'https:' && location.protocol !== 'https') {
        offerSocket = new WebSocket('ws://' + link);
    } else {
        offerSocket = new WebSocket('wss://' + link);
    }

    var bidForm = $('#Bid');

    var bidConfirm = $('#BidConfirm');
        bidConfirm.hide().removeClass('d-none');

    var bidFailure = $('#BidFailure');
        bidFailure.hide().removeClass('d-none');

    var user_id = {{ request.user.id|default_if_none:0 }};

    bidForm.submit(function(e){
        e.preventDefault();
        $(this).find('button').attr('disabled', true).html("<i class='fa fa-spinner fa-spin'></i>");
        $.ajax({
            type: "POST",
            url: bidForm.attr('action'),
            data: bidForm.serialize(),
            success: function(res) {
                bidForm.find('button').attr('disabled', false).text("Bid!");

                if (res.success) {
                    offerSocket.send(JSON.stringify({'status': 1}));
                } else {
                    var decoded = $("<div/>").html(res.message).text();
                    bidFailure.text(decoded).show().delay(5000).fadeOut();
                }
            }
        });
    });

    offerSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        $('#id_amount').val(data['must_bid']);
        $('#topBids').empty();

        bidConfirm.show().delay(5000).fadeOut();

        jQuery.each(data['top_bids'], function(index, value){
            var name = value['display_name'];

            if (value['anonymous'] && value['user_id'] !== user_id) {
                name = "Anonymous";
            }

            $('#topBids').append("<li class='list-group-item d-flex justify-content-between align-items-center'>" + name + "<strong>" + value['amount'] + "</strong></li>");
        });
    };

    offerSocket.onclose = function(e) {
        window.setTimeout(function(){
            window.location.href = "{% url 'offer:view' auction.user.slug auction.slug offer.user.slug offer.pk %}";
        }, 10000);
    };

</script>
{% endblock %}

{% block content %}

    <div class="row mb-3">
        <div class="col-md-9">
            <h1 class="mb-0">{{ offer.user }} {{ offer.category|lower }}</h1>
            {% if offer.tags.exists %}
                <h6 class="my-0">
                    {% for tag in offer.tags.all %}
                        <span><a href="{% url 'offer:search_tag' auction.user.slug auction.slug tag.slug %}">#{{ tag }}</a></span>
                    {% endfor %}
                </h6>
            {% endif %}
        </div>
        <div class="col-md-3 text-right">
        {% if auction.signups_open and request.user.id == offer.user.id %}
            <div class="btn-group">
                <a href="{% url 'offer:update' auction.user.slug auction.slug offer.user.slug offer.pk %}" class="btn btn-primary" title="Edit"><i class="fa fa-cog"></i> <span class="sr-only">Edit</span></a>
                <a href="{% url 'offer:delete' auction.user.slug auction.slug offer.user.slug offer.pk %}" class="btn btn-warning" title="Delete"><i class="fa fa-trash"></i> <span class="sr-only">Delete</span></a>
            </div>
        {% elif auction.user.id == request.user.id %}
            <div class="btn-group">
                <a href="{% url 'offer:update_administration' auction.user.slug auction.slug offer.pk %}" class="btn btn-primary" title="Edit"><i class="fa fa-cog"></i> <span class="sr-only">Edit</span></a>
                <a href="{% url 'offer:delete_administration' auction.user.slug auction.slug offer.pk %}" class="btn btn-warning" title="Delete"><i class="fa fa-trash"></i> <span class="sr-only">Delete</span></a>
            </div>
        {% endif %}
        </div>
    </div>

    {% if offer.image %}
        <div class="row">
            <div class="col-md-6">
                {% include "offer/_view_about.html" %}
            </div>
            <div class="col-md-6"><img src="{{ offer.image.url }}" class="img-fluid"></div>
        </div>
    {% else %}
        {% include "offer/_view_about.html" %}
    {% endif %}

    <hr>

    <div class="row">
        <div class="col-md-6">
            {% if auction.bidding_open %}
                <h3>Bid</h3>
                {% if request.user.is_authenticated %}
                    <form method="post" id="Bid" action="{% url 'offer:view' auction.user.slug auction.slug offer.user.slug offer.pk %}">
                        {% csrf_token %}
                        <p class="alert alert-warning">
                            <small><i class="fa fa-exclamation-triangle"></i> Bids cannot be deleted and there is no confirmation stage.
                            {% if offer.quantity > 1 %} <strong>If you have a top bid and bid again, it will be considered a bid for an additional item!</strong>{% endif %}</small>
                        </p>

                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">{{ auction.currency }}</span>
                            </div>
                            <input type="text" name="amount" value="{{ offer.must_bid }}" step="0.01" class="form-control" placeholder="Amount" title="" id="id_amount">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary">Bid!</button>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="form-check">
                                <input type="checkbox" name="anonymous" class="form-check-input" title="" id="id_anonymous">
                                <label class="form-check-label" for="id_anonymous">Anonymous</label>
                            </div>
                        </div>

                    </form>

                    <p class="alert alert-success d-none" id="BidConfirm">Thank you for bidding!</p>
                    <p class="alert alert-danger d-none" id="BidFailure"></p>

                {% else %}

                    <p class="alert alert-warning">You must be <a class="alert-link" href="{% url 'account:login' %}?next={% url 'offer:view' auction.user.slug auction.slug offer.user.slug offer.pk %}">logged in</a> to bid!</p>

                {% endif %}

            {% elif auction.bidding_period %}
                <h3>Bid</h3>
                <p>Bidding is open <strong>{{ auction.bidding_period }}</strong></p>

            {% endif %}
        </div>
        <div class="col-md-6">
            <h3>Top bids</h3>
            <ul id="topBids" class="list-group">
                {% for bid in offer.top_bids %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        {% if offer.quantity > 1 %}
                        {{ offer.category }} {{ forloop.counter }}:
                        {% endif %}
                        {% if not bid.anonymous or request.user.id == bid.user_id %}{{ bid.user }}{% else %}Anonymous{% endif %}
                        <strong>{% currency bid.amount auction.currency %}</strong>
                    </li>
                {% empty %}
                    <p class="text-muted">There are no bids to view</p>
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock %}

offer/templates/offer/winners.html
{% extends 'auction/base.html' %}
{% load bootstrap4 core_tags %}

{% block main %}

    <h1>Your winners</h1>

    {% if offer_list %}

        <table class="table">
            <tbody>
                {% for bid in offer_list %}
                <tr class="table-{% if bid.donation_complete %}success{% elif bid.donation_unverified %}info{% elif bid.pending_alert %}light{% elif bid.pending_donation %}warning{% elif bid.donation_late %}danger{% endif %}">
                    <td>{{ bid.offer.category }}</td>
                    <td>
                        {% if bid.donation_complete or not bid.anonymous %}
                            <a href="{% url 'account:profile' bid.user.slug %}">{{ bid.user }}</a>
                        {% else %}
                            Anonymous
                        {% endif %}
                    </td>
                    <td>{% currency bid.amount auction.currency %}</td>
                    <td class="text-right">
                        <a href="{% url 'offer:view' auction.user.slug auction.slug bid.offer.user.slug bid.offer.pk %}" class="btn btn-info btn-sm" title="View"><i class="fa fa-eye"></i> <span class="sr-only">View</span></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    {% else %}

        <p class="alert alert-info">You have no offers in this auction</p>

    {% endif %}

{% endblock %}

{% block side %}

    <h1>&nbsp;</h1>

    <ul class="list-group">
        <li class="list-group-item list-group-item-light">Pending administration</li>
        <li class="list-group-item list-group-item-warning">Pending donation</li>
        <li class="list-group-item list-group-item-info">Donation unverified</li>
        <li class="list-group-item list-group-item-success">Donation complete</li>
        <li class="list-group-item list-group-item-danger">Donation late</li>
    </ul>

{% endblock %}